// <auto-generated />
using System;
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Db.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20230103201409_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Objects.Entities.Books", b =>
                {
                    b.Property<string>("ISDN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISDN");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISDN = "111111111",
                            AuthorName = "Dan Brown",
                            IsBooked = false,
                            Title = "Da Vinci Code"
                        },
                        new
                        {
                            ISDN = "222222222",
                            AuthorName = "G.R.R Martin",
                            IsBooked = false,
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            ISDN = "333333333",
                            AuthorName = "george orwell",
                            IsBooked = false,
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("Objects.Entities.BookTransactions", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BooksISDN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISDN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MembersMemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("BooksISDN");

                    b.HasIndex("MembersMemberId");

                    b.ToTable("BookTransactions");
                });

            modelBuilder.Entity("Objects.Entities.Members", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = -536583742,
                            Name = "Stevie Bruen"
                        },
                        new
                        {
                            MemberId = -1842227606,
                            Name = "Rita Hammes"
                        },
                        new
                        {
                            MemberId = 19294850,
                            Name = "Uriah Paucek"
                        });
                });

            modelBuilder.Entity("Objects.Entities.BookTransactions", b =>
                {
                    b.HasOne("Objects.Entities.Books", null)
                        .WithMany("BookTransactions")
                        .HasForeignKey("BooksISDN");

                    b.HasOne("Objects.Entities.Members", null)
                        .WithMany("BookTransactions")
                        .HasForeignKey("MembersMemberId");
                });

            modelBuilder.Entity("Objects.Entities.Books", b =>
                {
                    b.Navigation("BookTransactions");
                });

            modelBuilder.Entity("Objects.Entities.Members", b =>
                {
                    b.Navigation("BookTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
